export type SavedRoute={id:number;from:string;to:string;label?:string;lastUsed?:string};
export type Point={x:number;y:number};
export type Place=Point&{name:string;short:string;icon:string};
export type UserPlace=Place&{id:string;address:string;category:string};
export type Accessibility='accessible'|'unverified'|'blocked';
export type Side='este'|'oeste'|'norte'|'sur';
export type SidewalkSegment={id:string;street:string;side:Side;from:Point;to:Point;accessibility:Accessibility;distance:string};
export type Crossing={id:string;intersection:string;connects:[string,string];from:Point;to:Point;accessibility:Accessibility;curbRamp:boolean};
export type RoutePathItem={kind:'sidewalk'|'crossing';id:string};
export type RoutePlan={from:string;to:string;points:Point[];states:('ok'|'warn')[];distance:string;time:string;steps:{text:string;detail:string;state:string;tone:string}[];detour?:boolean;message?:string;sidewalks:SidewalkSegment[];crossings:Crossing[];path:RoutePathItem[];warningSegmentIds:string[]};
export const user={name:'Ciro'};
export const locations:Record<string,Place>={
 'Mi ubicación':{name:'Mi ubicación',short:'Ubicación',icon:'●',x:12,y:82},Casa:{name:'Casa',short:'Casa',icon:'⌂',x:13,y:68},Trabajo:{name:'Trabajo',short:'Trabajo',icon:'▦',x:48,y:82},Escuela:{name:'Escuela',short:'Escuela',icon:'▤',x:80,y:72},Iglesia:{name:'Iglesia',short:'Iglesia',icon:'♜',x:16,y:22},Plaza:{name:'Plaza',short:'Plaza',icon:'♧',x:51,y:23},'Plaza Independencia':{name:'Plaza Independencia',short:'Plaza',icon:'♧',x:51,y:23},Hospital:{name:'Hospital',short:'Hospital',icon:'✚',x:83,y:18},Club:{name:'Club',short:'Club',icon:'⚑',x:78,y:45},Parque:{name:'Parque',short:'Parque',icon:'♧',x:49,y:46},'Centro Cultural':{name:'Centro Cultural',short:'C. Cultural',icon:'◆',x:25,y:46},'Centro cultural':{name:'Centro cultural',short:'C. Cultural',icon:'◆',x:25,y:46}};
export const destinations=['Mi ubicación','Casa','Trabajo','Escuela','Iglesia','Plaza','Hospital','Club','Parque','Centro Cultural'];
export const demoPlaces:UserPlace[]=[{id:'casa',name:'Casa',address:'Brasil 1550',category:'Casa',short:'Casa',icon:'⌂',x:13,y:68},{id:'escuela',name:'Escuela',address:'Espora 221',category:'Escuela',short:'Escuela',icon:'▤',x:80,y:72},{id:'trabajo',name:'Trabajo',address:'San Martín 850',category:'Trabajo',short:'Trabajo',icon:'▦',x:48,y:82},{id:'plaza',name:'Plaza',address:'Plaza Independencia',category:'Plaza',short:'Plaza',icon:'♧',x:51,y:23},{id:'hospital',name:'Hospital',address:'Hospital Central',category:'Hospital',short:'Hospital',icon:'✚',x:83,y:18},{id:'iglesia',name:'Iglesia',address:'Iglesia San José',category:'Iglesia',short:'Iglesia',icon:'♜',x:16,y:22},{id:'club',name:'Club',address:'Club Mendoza',category:'Club',short:'Club',icon:'⚑',x:78,y:45},{id:'centro-cultural',name:'Centro Cultural',address:'Centro Cultural Mendoza',category:'Otro',short:'C. Cultural',icon:'◆',x:25,y:46}];
export const placeCategories=['Casa','Escuela','Trabajo','Hospital','Iglesia','Plaza','Club','Otro'];
export const availableMapPositions:Point[]=[{x:42,y:68},{x:12,y:45},{x:48,y:45},{x:82,y:84},{x:16,y:84},{x:65,y:22}];
export const savedRoutes:SavedRoute[]=[{id:1,from:'Casa',to:'Escuela',label:'Camino a la escuela',lastUsed:'Hoy'},{id:2,from:'Casa',to:'Plaza',lastUsed:'Ayer'}];
export const accessibilityStates={accessible:{label:'Accesible',tone:'ok'},unverified:{label:'Sin verificar',tone:'warn'},blocked:{label:'No accesible',tone:'bad'}};
export const sidewalkSegments:SidewalkSegment[]=[
 {id:'los-andes-norte-01',street:'Los Andes',side:'norte',from:{x:13,y:64},to:{x:30,y:64},accessibility:'accessible',distance:'110 m'},
 {id:'los-andes-norte-02',street:'Los Andes',side:'norte',from:{x:30,y:64},to:{x:66,y:64},accessibility:'blocked',distance:'190 m'},
 {id:'los-andes-sur-01',street:'Los Andes',side:'sur',from:{x:30,y:72},to:{x:66,y:72},accessibility:'accessible',distance:'210 m'},
 {id:'los-andes-sur-02',street:'Los Andes',side:'sur',from:{x:66,y:72},to:{x:80,y:72},accessibility:'accessible',distance:'90 m'},
 {id:'las-heras-norte-01',street:'Las Heras',side:'norte',from:{x:16,y:22},to:{x:51,y:22},accessibility:'accessible',distance:'240 m'},
 {id:'trabajo-norte-01',street:'San Martín',side:'norte',from:{x:48,y:78},to:{x:66,y:78},accessibility:'accessible',distance:'130 m'},
 {id:'hospital-oeste-01',street:'Colón',side:'oeste',from:{x:66,y:78},to:{x:66,y:36},accessibility:'unverified',distance:'260 m'},
 {id:'hospital-norte-01',street:'Espejo',side:'norte',from:{x:66,y:36},to:{x:83,y:36},accessibility:'accessible',distance:'120 m'},
 {id:'colon-oeste-01',street:'Colón',side:'oeste',from:{x:30,y:72},to:{x:30,y:36},accessibility:'unverified',distance:'220 m'},
 {id:'espejo-sur-01',street:'Espejo',side:'sur',from:{x:30,y:36},to:{x:51,y:36},accessibility:'accessible',distance:'150 m'},
 {id:'colon-este-01',street:'Colón',side:'este',from:{x:66,y:72},to:{x:66,y:36},accessibility:'accessible',distance:'220 m'}
];
export const crossings:Crossing[]=[
 {id:'cruce-los-andes-colon-oeste',intersection:'Los Andes y Colón',connects:['los-andes-norte-01','los-andes-sur-01'],from:{x:30,y:64},to:{x:30,y:72},accessibility:'accessible',curbRamp:true},
 {id:'cruce-los-andes-rivadavia',intersection:'Los Andes y Rivadavia',connects:['los-andes-norte-02','los-andes-sur-02'],from:{x:66,y:64},to:{x:66,y:72},accessibility:'blocked',curbRamp:false}
];
type RouteScenario={path:RoutePathItem[];warningSegmentIds?:string[];distance:string;time:string;message?:string;detour?:boolean};
export const routeScenarios:Record<string,RouteScenario>={
 'Casa|Escuela':{path:[{kind:'sidewalk',id:'los-andes-norte-01'},{kind:'crossing',id:'cruce-los-andes-colon-oeste'},{kind:'sidewalk',id:'los-andes-sur-01'},{kind:'sidewalk',id:'los-andes-sur-02'}],warningSegmentIds:['los-andes-norte-02'],distance:'420 m',time:'18 min aprox.',detour:true,message:'Encontramos un recorrido alternativo porque una vereda del trayecto directo no es accesible.'},
 'Iglesia|Plaza':{path:[{kind:'sidewalk',id:'las-heras-norte-01'}],distance:'240 m',time:'10 min aprox.'},
 'Trabajo|Hospital':{path:[{kind:'sidewalk',id:'trabajo-norte-01'},{kind:'sidewalk',id:'hospital-oeste-01'},{kind:'sidewalk',id:'hospital-norte-01'}],distance:'510 m',time:'20 min aprox.'},
 'Casa|Plaza':{path:[{kind:'sidewalk',id:'los-andes-norte-01'},{kind:'crossing',id:'cruce-los-andes-colon-oeste'},{kind:'sidewalk',id:'colon-oeste-01'},{kind:'sidewalk',id:'espejo-sur-01'}],distance:'590 m',time:'22 min aprox.'},
 'Casa|Hospital':{path:[{kind:'sidewalk',id:'los-andes-norte-01'},{kind:'crossing',id:'cruce-los-andes-colon-oeste'},{kind:'sidewalk',id:'los-andes-sur-01'},{kind:'sidewalk',id:'colon-este-01'},{kind:'sidewalk',id:'hospital-norte-01'}],warningSegmentIds:['los-andes-norte-02'],distance:'730 m',time:'27 min aprox.',detour:true,message:'Recorrido recalculado para evitar una barrera en la vereda.'}
};
const stateInfo=(state:Accessibility)=>accessibilityStates[state];
const sideOffset:Record<Side,Point>={norte:{x:0,y:-1},sur:{x:0,y:1},este:{x:1,y:0},oeste:{x:-1,y:0}};
export const relativeSide=(segment:SidewalkSegment,travelFrom=segment.from,travelTo=segment.to):'derecha'|'izquierda'=>{const direction={x:travelTo.x-travelFrom.x,y:travelTo.y-travelFrom.y},offset=sideOffset[segment.side];return direction.x*offset.y-direction.y*offset.x<0?'izquierda':'derecha'};
const distanceSquared=(a:Point,b:Point)=>(a.x-b.x)**2+(a.y-b.y)**2;
const buildSteps=(path:RoutePathItem[],warningIds:string[],from:string,to:string,sidewalkData:SidewalkSegment[])=>{const steps:{text:string;detail:string;state:string;tone:string}[]=[];let cursor=locations[from]||locations['Mi ubicación'];let sidewalkIndex=0;path.forEach(item=>{const routePart=item.kind==='sidewalk'?sidewalkData.find(x=>x.id===item.id):crossings.find(x=>x.id===item.id);if(!routePart)return;const reversed=distanceSquared(cursor,routePart.to)<distanceSquared(cursor,routePart.from),travelFrom=reversed?routePart.to:routePart.from,travelTo=reversed?routePart.from:routePart.to;cursor=travelTo;if(item.kind==='sidewalk'){const segment=routePart as SidewalkSegment,state=stateInfo(segment.accessibility),side=relativeSide(segment,travelFrom,travelTo);steps.push({text:`${sidewalkIndex?'Continuá':'Avanzá'} por ${segment.street} por la vereda de tu ${side}`,detail:segment.distance,state:state.label,tone:state.tone});const warning=warningIds.map(id=>sidewalkData.find(x=>x.id===id)).find(Boolean);if(warning&&sidewalkIndex===0){const warningSide=relativeSide(warning,travelFrom,travelTo);steps.push({text:'Hay una barrera más adelante. No continúes por esa vereda',detail:`La vereda de tu ${warningSide} está obstruida en ${warning.street}`,state:'No accesible',tone:'bad'})}sidewalkIndex++}else{const crossing=routePart as Crossing,state=stateInfo(crossing.accessibility);steps.push({text:`En ${crossing.intersection}, cruzá por el cruce accesible`,detail:`Cruce accesible${crossing.curbRamp?' · Rebaje de cordón verificado':''}`,state:state.label,tone:state.tone})}});steps.push({text:`Llegaste a ${to}`,detail:'Destino',state:'Accesible',tone:'ok'});return steps};
const fallbackScenario=(from:string,to:string)=>{const a=locations[from]||locations['Mi ubicación'],b=locations[to]||locations.Plaza,corner={x:b.x,y:a.y};const generated:SidewalkSegment[]=[{id:'ruta-local-01',street:'Recorrido local',side:'norte',from:a,to:corner,accessibility:'accessible',distance:'180 m'},{id:'ruta-local-02',street:'Recorrido local',side:'este',from:corner,to:b,accessibility:'unverified',distance:'160 m'}];const path:RoutePathItem[]=generated.map(x=>({kind:'sidewalk',id:x.id}));return{generated,path,distance:'340 m',time:'16 min aprox.'}};
export function getRoutePlan(from:string,to:string):RoutePlan{const scenario=routeScenarios[`${from}|${to}`];let sidewalks=sidewalkSegments,path:RoutePathItem[],distance:string,time:string,message:string|undefined,detour=false,warningSegmentIds:string[]=[];if(scenario){({path,distance,time,message}=scenario);detour=!!scenario.detour;warningSegmentIds=scenario.warningSegmentIds||[]}else{const fallback=fallbackScenario(from,to);sidewalks=[...sidewalkSegments,...fallback.generated];path=fallback.path;distance=fallback.distance;time=fallback.time}const pathPoints:Point[]=[];path.forEach(item=>{const segment=item.kind==='sidewalk'?sidewalks.find(x=>x.id===item.id):crossings.find(x=>x.id===item.id);if(segment){if(!pathPoints.length)pathPoints.push(segment.from);pathPoints.push(segment.to)}});const states=path.filter(x=>x.kind==='sidewalk').map(item=>sidewalks.find(x=>x.id===item.id)?.accessibility==='unverified'?'warn' as const:'ok' as const);return{from,to,points:pathPoints,states,distance,time,steps:buildSteps(path,warningSegmentIds,from,to,sidewalks),detour,message,sidewalks,crossings,path,warningSegmentIds}}
export const routes=['Casa → Escuela','Iglesia → Plaza','Trabajo → Hospital','Casa → Hospital'];
export const barrierTypes=['Vereda rota','Falta de rampa','Rampa bloqueada','Obstáculo en la vereda','Cruce inaccesible','Entrada no accesible','Otro'];
export const reports=[{id:1,location:'Av. España y Espejo',type:'Vereda rota'}];
export const tutorials=[{id:1,title:'Moverse por la ciudad',icon:'⌖',duration:'4 min',desc:'Planificá recorridos y reconocé cruces seguros.'},{id:2,title:'Subir y bajar escalones',icon:'↗',duration:'6 min',desc:'Técnicas prácticas para distintos tipos de escalón.'},{id:3,title:'Rampas y desniveles',icon:'⌁',duration:'5 min',desc:'Cómo abordar pendientes con mayor seguridad.',youtubeId:'MuSoLag_meo'},{id:4,title:'Mantenimiento de la silla',icon:'◉',duration:'8 min',desc:'Controles simples para mantener todo en marcha.'},{id:5,title:'Cambiar una rueda',icon:'◎',duration:'7 min',desc:'Una guía clara, paso a paso.'},{id:6,title:'Seguridad y autonomía',icon:'✓',duration:'5 min',desc:'Hábitos útiles para moverte con confianza.'}];
export const api={getRoute:async(from:string,to:string)=>getRoutePlan(from,to),getSavedRoutes:async()=>savedRoutes,saveRoute:async(route:SavedRoute)=>route,deleteSavedRoute:async(id:number)=>id,updateUser:async(name:string)=>({name}),createReport:async(report:unknown)=>({ok:true,report}),getTutorials:async()=>tutorials};
