'use client';
import{useEffect,useState}from'react';import{savedRoutes as initialRoutes,getRoutePlan,relativeSide,locations,demoPlaces,placeCategories,availableMapPositions,barrierTypes,tutorials,type SavedRoute,type RoutePlan,type UserPlace,type Place}from'./mockData';
type Screen='welcome'|'createProfile'|'home'|'profile'|'myPlaces'|'placeForm'|'routesHub'|'newRoute'|'savedRoutes'|'map'|'detail'|'report'|'confirm'|'thanks'|'tutorials'|'tutorial';
const KEY='rodando-user-name',CONTRAST='rodando-high-contrast',PLACES='rodando-user-places',SAVED_ROUTES='rodando-saved-routes',MANUAL='__manual__';
function Button({children,onClick,secondary,disabled}:{children:React.ReactNode,onClick?:()=>void,secondary?:boolean,disabled?:boolean}){return <button className={secondary?'secondary-button':'primary-button'} onClick={onClick} disabled={disabled}>{children}</button>}
function Header({title,onBack,onProfile,name}:{title?:string,onBack?:()=>void,onProfile:()=>void,name:string}){const initial=(name.trim()[0]||'?').toLocaleUpperCase('es');return <header className="topbar">{onBack?<button className="back-button" onClick={onBack} aria-label="Volver">←</button>:<span className="header-logo-frame"><img className="header-logo" src="/logo-circular-rodando-x-mza.png" alt="Rodando X MZA"/></span>}<strong>{title||'RODANDO X MZA'}</strong><button className="avatar" onClick={onProfile} aria-label={`Abrir perfil de ${name}`}>{initial}</button></header>}
type MainSection='home'|'routesHub'|'report'|'tutorials';
function Nav({active,go}:{active:MainSection,go:(s:Screen)=>void}){return <nav className="bottom-nav" aria-label="Navegación principal">{([['home','⌂','Inicio'],['routesHub','⌁','Recorridos'],['report','＋','Reportar'],['tutorials','▶','Tutoriales']]as const).map(([s,i,l])=><button key={s} className={active===s?'active':''} aria-current={active===s?'page':undefined} onClick={()=>go(s)}><span>{i}</span>{l}</button>)}</nav>}
function Page({title,intro,children}:{title:string,intro?:string,children:React.ReactNode}){return <section className="page-content"><p className="eyebrow">Rodando por Mendoza</p><h1>{title}</h1>{intro&&<p className="page-intro">{intro}</p>}{children}</section>}
function Feature({icon,title,sub,onClick}:{icon:string,title:string,sub:string,onClick:()=>void}){return <button className="feature-card" onClick={onClick}><span className="feature-icon">{icon}</span><span><strong>{title}</strong><small>{sub}</small></span><b>›</b></button>}
function Badge({tone,label}:{tone:string,label:string}){return <span className={`badge ${tone}`}><b>{tone==='ok'?'✓':tone==='warn'?'?':'×'}</b>{label}</span>}
function MapCanvas({plan,placeMap}:{plan:RoutePlan,placeMap:Record<string,Place>}){
 const lineStyle=(a:{x:number;y:number},b:{x:number;y:number})=>a.y===b.y?{left:`${Math.min(a.x,b.x)}%`,top:`${a.y}%`,width:`${Math.abs(b.x-a.x)}%`}:{left:`${a.x}%`,top:`${Math.min(a.y,b.y)}%`,height:`${Math.abs(b.y-a.y)}%`};
 const midpoint=(a:{x:number;y:number},b:{x:number;y:number})=>({left:`${(a.x+b.x)/2}%`,top:`${(a.y+b.y)/2}%`});
 const selectedIds=new Set(plan.path.map(x=>x.id));
 const streetAxisPoint=(point:{x:number;y:number},side:'norte'|'sur'|'este'|'oeste')=>side==='norte'?{x:point.x,y:point.y+4}:side==='sur'?{x:point.x,y:point.y-4}:side==='oeste'?{x:point.x+4,y:point.y}:{x:point.x-4,y:point.y};
 const visibleRoute=plan.path.flatMap(item=>{if(item.kind!=='sidewalk')return[];const segment=plan.sidewalks.find(x=>x.id===item.id);return segment?[{id:item.id,from:streetAxisPoint(segment.from,segment.side),to:streetAxisPoint(segment.to,segment.side)}]:[]});
 const routeStart=visibleRoute[0]?.from||plan.points[0],routeEnd=visibleRoute.at(-1)?.to||plan.points.at(-1)!;
 return <div className="city-map navigation-map" role="img" aria-label={`Mapa del recorrido recomendado de ${plan.from} a ${plan.to}`}>
  <span className="map-simulation">MAPA DE RECORRIDO</span><div className="green-zone park-one"/><div className="green-zone park-two"/><div className="urban-block block-one"/><div className="urban-block block-two"/><div className="urban-block block-three"/><div className="road road-h r1"><small>ESPEJO</small></div><div className="road road-h r2"><small>LAS HERAS</small></div><div className="road road-h r3"><small>LOS ANDES</small></div><div className="road road-v c1"><small>COLÓN</small></div><div className="road road-v c2"><small>SAN MARTÍN</small></div><div className="road road-v c3"><small>ESPAÑA</small></div>
  <div className="navigation-route">{visibleRoute.map(segment=><i key={`route-${segment.id}`} className="navigation-route-segment" style={lineStyle(segment.from,segment.to)}/>)}</div>
  {plan.crossings.filter(x=>selectedIds.has(x.id)).map(crossing=><span key={`cross-${crossing.id}`} className="accessible-crossing" style={midpoint(crossing.from,crossing.to)} title="Cruce accesible"><b aria-hidden="true">↕</b><small>Cruce</small></span>)}
  {plan.sidewalks.filter(x=>plan.warningSegmentIds.includes(x.id)).map(segment=>{const from=streetAxisPoint(segment.from,segment.side),to=streetAxisPoint(segment.to,segment.side);return <span key={`blocked-${segment.id}`} className="blocked-sidewalk" style={midpoint(from,to)} title="Barrera relevante"><b aria-hidden="true">×</b><small>Barrera</small></span>})}
  {Object.values(placeMap).map(p=>{const selected=p.name===plan.from||p.name===plan.to;return <span key={p.name} className={`map-place ${selected?'selected':''}`} style={{left:`${p.x}%`,top:`${p.y}%`}}><b>{p.icon}</b><small>{p.short}</small></span>})}
  <span className="route-pin origin-pin" style={{left:`${routeStart.x}%`,top:`${routeStart.y}%`}}>A</span><span className="route-pin destination-pin" style={{left:`${routeEnd.x}%`,top:`${routeEnd.y}%`}}>B</span>
 </div>
}
function accessibilityLabel(state:string){return state==='accessible'?'Accesible':state==='unverified'?'Sin verificar':'No accesible'}
export default function Home(){const[ready,setReady]=useState(false),[screen,setScreen]=useState<Screen>('welcome'),[name,setName]=useState(''),[draftName,setDraftName]=useState(''),[contrast,setContrast]=useState(false),[origin,setOrigin]=useState('Mi ubicación'),[destination,setDestination]=useState('Plaza'),[originChoice,setOriginChoice]=useState('Mi ubicación'),[destinationChoice,setDestinationChoice]=useState('Plaza'),[manualOrigin,setManualOrigin]=useState(''),[manualDestination,setManualDestination]=useState(''),[saveOriginPlace,setSaveOriginPlace]=useState(false),[saveDestinationPlace,setSaveDestinationPlace]=useState(false),[originPlaceName,setOriginPlaceName]=useState(''),[destinationPlaceName,setDestinationPlaceName]=useState(''),[saved,setSaved]=useState<SavedRoute[]>(initialRoutes),[saveLabel,setSaveLabel]=useState(''),[savedNotice,setSavedNotice]=useState(false),[recalculated,setRecalculated]=useState(false),[type,setType]=useState(''),[location,setLocation]=useState(''),[photo,setPhoto]=useState(false),[description,setDescription]=useState(''),[tutorial,setTutorial]=useState(tutorials[0]),[places,setPlaces]=useState<UserPlace[]>(demoPlaces),[editingPlace,setEditingPlace]=useState<UserPlace|null>(null),[placeName,setPlaceName]=useState(''),[placeAddress,setPlaceAddress]=useState(''),[placeCategory,setPlaceCategory]=useState('Casa'),[placesReturn,setPlacesReturn]=useState<Screen>('profile'),[mapReturn,setMapReturn]=useState<Screen>('newRoute');
useEffect(()=>{const n=localStorage.getItem(KEY)||'';const c=localStorage.getItem(CONTRAST)==='true';const stored=localStorage.getItem(PLACES),storedRoutes=localStorage.getItem(SAVED_ROUTES);setName(n);setDraftName(n);setContrast(c);if(stored)try{setPlaces(JSON.parse(stored))}catch{}if(storedRoutes)try{setSaved(JSON.parse(storedRoutes))}catch{}setScreen(n?'home':'welcome');setReady(true)},[]);
const go=(s:Screen)=>{setScreen(s);window.scrollTo(0,0)};const resetRouteDraft=()=>{setOriginChoice('Mi ubicación');setDestinationChoice('Plaza');setManualOrigin('');setManualDestination('');setSaveOriginPlace(false);setSaveDestinationPlace(false);setOriginPlaceName('');setDestinationPlaceName('');setSaveLabel('');setSavedNotice(false)};const beginNewRoute=()=>{resetRouteDraft();go('newRoute')};const openPlacesFrom=(from:Screen)=>{setPlacesReturn(from);go('myPlaces')};const saveName=()=>{const n=draftName.trim();if(!n)return;localStorage.setItem(KEY,n);setName(n);go('home')};const logout=()=>{localStorage.removeItem(KEY);resetRouteDraft();setName('');setDraftName('');go('welcome')};const toggleContrast=()=>{const v=!contrast;setContrast(v);localStorage.setItem(CONTRAST,String(v))};const persistSaved=(next:SavedRoute[])=>{setSaved(next);localStorage.setItem(SAVED_ROUTES,JSON.stringify(next))};const runSaved=(r:SavedRoute)=>{setOrigin(r.from);setDestination(r.to);setRecalculated(true);setMapReturn('savedRoutes');go('map')};const addSaved=()=>{persistSaved([...saved,{id:Date.now(),from:origin,to:destination,label:saveLabel||undefined,lastUsed:'Ahora'}]);setSavedNotice(true)};
const persistPlaces=(next:UserPlace[])=>{setPlaces(next);localStorage.setItem(PLACES,JSON.stringify(next))};const openPlaceForm=(place:UserPlace|null)=>{setEditingPlace(place);setPlaceName(place?.name||'');setPlaceAddress(place?.address||'');setPlaceCategory(place?.category||'Casa');go('placeForm')};const savePlace=()=>{if(!placeName.trim()||!placeAddress.trim())return;if(editingPlace){persistPlaces(places.map(p=>p.id===editingPlace.id?{...p,name:placeName.trim(),short:placeName.trim(),address:placeAddress.trim(),category:placeCategory}:p))}else{const pos=availableMapPositions.find(candidate=>!places.some(p=>p.x===candidate.x&&p.y===candidate.y))||availableMapPositions[places.length%availableMapPositions.length];persistPlaces([...places,{id:`lugar-${Date.now()}`,name:placeName.trim(),short:placeName.trim(),address:placeAddress.trim(),category:placeCategory,icon:placeCategory==='Casa'?'⌂':'●',...pos}])}go('myPlaces')};
const pointForAddress=(address:string)=>{const hash=[...address].reduce((sum,c)=>sum+c.charCodeAt(0),0);return{x:14+(hash%6)*13,y:20+(Math.floor(hash/6)%6)*12}};const startRoute=()=>{const from=originChoice===MANUAL?manualOrigin.trim():originChoice,to=destinationChoice===MANUAL?manualDestination.trim():destinationChoice;if(!from||!to||from===to)return;let next=[...places];const maybeSave=(enabled:boolean,label:string,address:string)=>{if(enabled&&label.trim()&&address.trim()&&!next.some(p=>p.name===label.trim())){next.push({id:`lugar-${Date.now()}-${next.length}`,name:label.trim(),short:label.trim(),address:address.trim(),category:'Otro',icon:'●',...pointForAddress(address.trim())})}};maybeSave(saveOriginPlace,originPlaceName,manualOrigin);maybeSave(saveDestinationPlace,destinationPlaceName,manualDestination);if(next.length!==places.length)persistPlaces(next);setOrigin(from);setDestination(to);setRecalculated(false);setMapReturn('newRoute');go('map')};
const placeMap:Record<string,Place>=Object.fromEntries(places.map(p=>[p.name,p]));const addTemporary=(value:string)=>{if(value&&value!=='Mi ubicación'&&!placeMap[value]&&!locations[value])placeMap[value]={name:value,short:'Dirección',icon:'●',...pointForAddress(value)}};addTemporary(manualOrigin.trim());addTemporary(manualDestination.trim());addTemporary(origin);addTemporary(destination);Object.assign(locations,placeMap);const routeOptions=[{name:'Mi ubicación'},...places.map(p=>({name:p.name}))];const plan=getRoutePlan(origin,destination);if(!ready)return null;
if(screen==='welcome')return <main className={`welcome-shell ${contrast?'high-contrast':''}`}><section className="welcome"><img className="welcome-logo" src="/logo-rodando-x-mza.png" alt="Rodando X MZA, Mendoza accesible para todos"/><div className="welcome-message"><h1>Movete por Mendoza de forma más accesible.</h1><p>Encontrá recorridos accesibles, guardá tus trayectos frecuentes y compartí información sobre barreras en el camino.</p></div><Button onClick={()=>go('createProfile')}>Comenzar</Button></section></main>;
if(screen==='createProfile')return <main className={`welcome-shell profile-welcome-shell ${contrast?'high-contrast':''}`}><section className="profile-onboarding"><div className="profile-onboarding-logo"><img src="/logo-circular-rodando-x-mza.png" alt="Rodando X MZA"/></div><div className="profile-create"><div className="profile-intro"><p className="eyebrow">Tu ciudad, a tu manera</p><h1>¡Bienvenido/a a<br/><span>Rodando X MZA!</span></h1><p>Queremos conocerte un poquito.</p></div><label>¿Cómo querés que te llamemos?<input autoFocus value={draftName} onChange={e=>setDraftName(e.target.value)} placeholder="Ej. Ciro" onKeyDown={e=>e.key==='Enter'&&saveName()}/></label><Button disabled={!draftName.trim()} onClick={saveName}>Continuar</Button></div></section></main>;
let content:React.ReactNode;let back:(()=>void)|undefined;
if(screen==='home')content=<section className="home-content"><p className="eyebrow">Tu ciudad, a tu manera</p><h1>¡Hola, {name}! 👋<br/>¿A dónde querés ir hoy?</h1><div className="feature-grid"><Feature icon="⌁" title="Recorridos accesibles" sub="Encontrá el mejor camino" onClick={()=>go('routesHub')}/><Feature icon="★" title="Mis recorridos" sub="Volvé a tus destinos frecuentes" onClick={()=>go('savedRoutes')}/><Feature icon="!" title="Reportar una barrera" sub="Ayudá a mejorar la ciudad" onClick={()=>go('report')}/><Feature icon="▶" title="Tutoriales" sub="Consejos para tu autonomía" onClick={()=>go('tutorials')}/></div></section>;
else if(screen==='profile'){back=()=>go('home');content=<Page title="Perfil"><div className="profile-name"><span>{(name[0]||'?').toLocaleUpperCase('es')}</span><div><small>Tu nombre</small><strong>{name}</strong></div></div><label>Cambiar nombre<input value={draftName} onChange={e=>setDraftName(e.target.value)}/></label><button className="compact-save" onClick={saveName}>Guardar nombre</button><div className="settings-list"><button onClick={()=>go('savedRoutes')}>Mis recorridos <b>›</b></button><button onClick={()=>openPlacesFrom('profile')}>Mis lugares <b>›</b></button><button disabled>Preferencias de accesibilidad <small>Próximamente</small></button><label className="contrast-toggle">Modo alto contraste <input type="checkbox" checked={contrast} onChange={toggleContrast}/></label><button onClick={()=>alert('Ayuda simulada para este prototipo.')}>Ayuda <b>›</b></button></div><Button secondary onClick={logout}>Cerrar sesión</Button></Page>}
else if(screen==='myPlaces'){back=()=>go(placesReturn);content=<Page title="Mis lugares" intro="Guardá tus lugares frecuentes para encontrarlos rápidamente al crear un recorrido."><div className="places-list">{places.map(p=><article key={p.id}><span className="place-icon">{p.icon}</span><div><small>{p.category}</small><h2>{p.name}</h2><p>{p.address}</p></div><div className="place-actions"><button onClick={()=>openPlaceForm(p)} aria-label={`Editar ${p.name}`}>Editar</button><button onClick={()=>persistPlaces(places.filter(x=>x.id!==p.id))} aria-label={`Eliminar ${p.name}`}>Eliminar</button></div></article>)}</div><Button onClick={()=>openPlaceForm(null)}>Agregar lugar</Button></Page>}
else if(screen==='placeForm'){back=()=>go('myPlaces');content=<Page title={editingPlace?'Editar lugar':'Agregar lugar'} intro="La posición en el mapa es simulada y permanecerá fija."><label>Nombre del lugar<input value={placeName} onChange={e=>setPlaceName(e.target.value)} placeholder="Ej. Casa"/></label><label>Dirección<input value={placeAddress} onChange={e=>setPlaceAddress(e.target.value)} placeholder="Ej. Brasil 1550"/></label><label>Categoría<select value={placeCategory} onChange={e=>setPlaceCategory(e.target.value)}>{placeCategories.map(c=><option key={c}>{c}</option>)}</select></label><Button disabled={!placeName.trim()||!placeAddress.trim()} onClick={savePlace}>Guardar lugar</Button></Page>}
else if(screen==='routesHub')content=<Page title="Recorridos" intro="Encontrá rutas accesibles o volvé rápidamente a tus recorridos frecuentes."><div className="hub-grid"><Feature icon="＋" title="Nuevo recorrido" sub="Buscá una ruta accesible" onClick={beginNewRoute}/><Feature icon="★" title="Mis recorridos" sub="Tus destinos frecuentes" onClick={()=>go('savedRoutes')}/></div></Page>;
else if(screen==='newRoute'){back=()=>go('routesHub');content=<Page title="Nuevo recorrido" intro="Elegí un lugar guardado o ingresá otra dirección."><div className="route-endpoint"><label>Origen<select value={originChoice} onChange={e=>setOriginChoice(e.target.value)}>{routeOptions.map(x=><option key={x.name}>{x.name}</option>)}<option value={MANUAL}>+ Ingresar otra dirección</option></select></label>{originChoice===MANUAL&&<div className="manual-address"><label>Dirección<input value={manualOrigin} onChange={e=>setManualOrigin(e.target.value)} placeholder="Ej. San Martín 1200"/></label><label className="save-place-check"><input type="checkbox" checked={saveOriginPlace} onChange={e=>setSaveOriginPlace(e.target.checked)}/> Guardar este lugar</label>{saveOriginPlace&&<label>¿Cómo querés llamar a este lugar?<input value={originPlaceName} onChange={e=>setOriginPlaceName(e.target.value)} placeholder="Ej. Consultorio"/></label>}</div>}</div><button className="swap" onClick={()=>{const choice=originChoice,address=manualOrigin,save=saveOriginPlace,label=originPlaceName;setOriginChoice(destinationChoice);setManualOrigin(manualDestination);setSaveOriginPlace(saveDestinationPlace);setOriginPlaceName(destinationPlaceName);setDestinationChoice(choice);setManualDestination(address);setSaveDestinationPlace(save);setDestinationPlaceName(label)}} aria-label="Intercambiar origen y destino">⇅</button><div className="route-endpoint"><label>Destino<select value={destinationChoice} onChange={e=>setDestinationChoice(e.target.value)}>{routeOptions.map(x=><option key={x.name}>{x.name}</option>)}<option value={MANUAL}>+ Ingresar otra dirección</option></select></label>{destinationChoice===MANUAL&&<div className="manual-address"><label>Dirección<input value={manualDestination} onChange={e=>setManualDestination(e.target.value)} placeholder="Ej. Av. Colón 550"/></label><label className="save-place-check"><input type="checkbox" checked={saveDestinationPlace} onChange={e=>setSaveDestinationPlace(e.target.checked)}/> Guardar este lugar</label>{saveDestinationPlace&&<label>¿Cómo querés llamar a este lugar?<input value={destinationPlaceName} onChange={e=>setDestinationPlaceName(e.target.value)} placeholder="Ej. Consultorio"/></label>}</div>}</div><Button disabled={(originChoice===MANUAL?!manualOrigin.trim():!originChoice)||(destinationChoice===MANUAL?!manualDestination.trim():!destinationChoice)} onClick={startRoute}>Buscar recorrido accesible</Button><button className="manage-places-link" onClick={()=>openPlacesFrom('newRoute')}>Administrar mis lugares</button></Page>}
else if(screen==='savedRoutes'){back=()=>go('routesHub');content=<Page title="Mis recorridos" intro="Guardamos origen y destino; la ruta se recalcula cada vez."><div className="saved-list">{saved.map(r=><article key={r.id}><small>{r.label||'Recorrido frecuente'}</small><h2>{r.from} → {r.to}</h2><p>Última consulta: {r.lastUsed||'Sin consultas'}</p><Button onClick={()=>runSaved(r)}>Buscar ruta accesible ahora</Button><button className="delete-route" onClick={()=>persistSaved(saved.filter(y=>y.id!==r.id))}>Eliminar recorrido</button></article>)}{!saved.length&&<p>No tenés recorridos guardados todavía.</p>}</div><Button onClick={beginNewRoute}>Nuevo recorrido</Button></Page>}
else if(screen==='map'){back=()=>go(mapReturn);content=<section className="map-page"><MapCanvas plan={plan} placeMap={placeMap}/><article className="route-card"><p className="eyebrow">Ruta accesible encontrada</p><h2>{plan.from} → {plan.to}</h2>{plan.message&&<div className="detour-note"><b>Ruta alternativa accesible</b><span>{plan.message}</span></div>}{recalculated&&<div className="update-note"><b>↻ Ruta actualizada</b><span>Encontramos una ruta diferente porque cambió la accesibilidad de un tramo.</span><span>Ruta actualizada con la información disponible.</span></div>}<div className="stats"><strong>{plan.distance}</strong><span>•</span><strong>{plan.time}</strong></div><div className="notice">{plan.states.includes('warn')?'? Hay un tramo de vereda sin verificar.':'✓ El recorrido utiliza veredas y cruces accesibles.'}</div><div className="map-actions"><Button onClick={()=>go('detail')}>Ver detalle</Button><Button secondary onClick={addSaved}>Guardar recorrido</Button></div><label className="save-label">Nombre opcional<input value={saveLabel} onChange={e=>setSaveLabel(e.target.value)} placeholder="Ej. Camino a la escuela"/></label>{savedNotice&&<p role="status" className="saved-confirmation">✓ Recorrido guardado.</p>}</article></section>}
else if(screen==='detail'){back=()=>go('map');content=<Page title="Detalle del recorrido" intro={`${plan.from} → ${plan.to}`}><div className="steps">{plan.steps.map((x,i)=><article className="step" key={`${x.text}-${i}`}><span className="step-number">{i+1}</span><div><h3>{x.text}</h3><p>{x.detail}</p><Badge tone={x.tone} label={x.state}/></div></article>)}</div></Page>}
else if(screen==='report'){content=<Page title="Reportar una barrera" intro="Tu aporte puede ayudar a otras personas."><label>Ubicación<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Ej. Av. España y Espejo"/></label><div className="location-actions"><button onClick={()=>setLocation('Ubicación actual · Ciudad de Mendoza')}>⌖ Usar ubicación actual</button><button onClick={()=>setLocation('Punto marcado en el mapa simulado')}>⌖ Marcar en el mapa</button></div><fieldset><legend>Tipo de barrera</legend><div className="chips">{barrierTypes.map(x=><button className={type===x?'selected':''} onClick={()=>setType(x)} key={x}>{x}</button>)}</div></fieldset><label className="photo-box"><span>{photo?'✓ Foto simulada agregada':'▣ Agregar foto'}</span><input type="file" onChange={()=>setPhoto(true)}/></label><label>Descripción (opcional)<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><Button disabled={!location||!type} onClick={()=>go('confirm')}>Continuar</Button></Page>}
else if(screen==='confirm'){back=()=>go('report');content=<Page title="Confirmar reporte"><div className="summary"><div><small>Ubicación</small><strong>{location}</strong></div><div><small>Tipo</small><strong>{type}</strong></div><div><small>Descripción</small><strong>{description||'Sin descripción'}</strong></div></div><Button onClick={()=>go('thanks')}>Enviar reporte</Button></Page>}
else if(screen==='thanks'){content=<section className="confirmation"><div className="thanks-icon">✓</div><h1>¡Gracias por colaborar!</h1><p>Tu reporte fue registrado.</p><Button onClick={()=>go('home')}>Volver al inicio</Button></section>}
else if(screen==='tutorials')content=<Page title="Tutoriales" intro="Consejos y técnicas para moverte con mayor autonomía."><div className="tutorial-grid">{tutorials.map(t=><button className="tutorial-card" onClick={()=>{setTutorial(t);go('tutorial')}} key={t.id}><span>{t.icon}</span><div><h3>{t.title}</h3><small>{t.duration}</small><p>{t.desc}</p></div><b>›</b></button>)}</div></Page>;
else{back=()=>go('tutorials');content=<Page title={tutorial.title} intro="Contenido educativo desarrollado junto a especialistas.">{tutorial.youtubeId?<div className="video video-frame"><iframe src={`https://www.youtube-nocookie.com/embed/${tutorial.youtubeId}`} title={`Video del tutorial: ${tutorial.title}`} allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen loading="lazy"/></div>:<button className="video simulated-video" onClick={()=>alert('Reproducción simulada.')} aria-label={`Reproducir tutorial: ${tutorial.title}`}><span aria-hidden="true">▶</span><small>VIDEO · {tutorial.duration}</small></button>}<p className="body-copy">{tutorial.desc}</p></Page>}
const navSection:Partial<Record<Screen,MainSection>>={home:'home',profile:'home',myPlaces:placesReturn==='newRoute'?'routesHub':'home',routesHub:'routesHub',savedRoutes:'routesHub',map:'routesHub',detail:'routesHub',report:'report',tutorials:'tutorials',tutorial:'tutorials'};
const activeSection=navSection[screen];
return <main className={`app-shell ${contrast?'high-contrast':''}`}><Header name={name} onProfile={()=>go('profile')} onBack={back}/>{content}{activeSection&&<Nav active={activeSection} go={go}/>}</main>}
