'use client';
import{useState}from'react';import{destinations,routeSteps,barrierTypes,tutorials,api}from'./mockData';
type Screen='welcome'|'home'|'routes'|'map'|'detail'|'report'|'confirm'|'thanks'|'tutorials'|'tutorial';
const icons={home:'⌂',map:'⌖',report:'＋',tutorials:'▶'};
function Header({title,onBack}:{title?:string,onBack?:()=>void}){return <header className="topbar">{onBack?<button onClick={onBack} aria-label="Volver">←</button>:<div className="mini-logo">R</div>}<strong>{title||<>RODANDO <span>X MZA</span></>}</strong><button aria-label="Ayuda">?</button></header>}
function BottomNav({screen,go}:{screen:Screen,go:(s:Screen)=>void}){return <nav className="bottom-nav" aria-label="Navegación principal">{([['home','Inicio'],['map','Mapa'],['report','Reportar'],['tutorials','Tutoriales']]as const).map(([s,l])=><button key={s} className={screen===s?'active':''} onClick={()=>go(s)}><span>{icons[s]}</span>{l}</button>)}</nav>}
function Button({children,onClick,secondary=false,disabled=false}:{children:React.ReactNode,onClick?:()=>void,secondary?:boolean,disabled?:boolean}){return <button disabled={disabled} onClick={onClick} className={secondary?'secondary-button':'primary-button'}>{children}</button>}
function Badge({tone,label}:{tone:string,label:string}){return <span className={`badge ${tone}`}><b>{tone==='ok'?'✓':tone==='warn'?'!':'×'}</b>{label}</span>}
function MapVisual(){return <div className="map-visual" role="img" aria-label="Mapa simulado con ruta accesible desde Mi ubicación hasta Plaza Independencia"><div className="map-block b1"/><div className="map-block b2"/><div className="map-block b3"/><div className="street s1"/><div className="street s2"/><div className="route-path"/><span className="pin start">A</span><span className="pin end">B</span><span className="poi">♜</span><span className="caution">!</span></div>}
export default function Home(){const[screen,setScreen]=useState<Screen>('welcome');const[origin,setOrigin]=useState('Mi ubicación');const[destination,setDestination]=useState('Plaza Independencia');const[type,setType]=useState('');const[location,setLocation]=useState('');const[photo,setPhoto]=useState(false);const[description,setDescription]=useState('');const[selectedTutorial,setSelectedTutorial]=useState(tutorials[0]);const go=(s:Screen)=>{setScreen(s);scrollTo(0,0)};
if(screen==='welcome')return <main className="welcome-shell"><section className="welcome"><div className="brand-mark">R</div><p className="eyebrow">Mendoza accesible</p><h1>RODANDO <span>X MZA</span></h1><p className="welcome-copy">Movete por Mendoza de manera más accesible.</p><div className="city-scene" aria-hidden="true"><div className="sun"/><div className="mountain mountain-one"/><div className="mountain mountain-two"/><div className="buildings"><i/><i/><i/><i/></div><div className="route-line"/><div className="wheelchair"><b>●</b><span>◯</span></div></div><Button onClick={()=>go('home')}>Comenzar →</Button></section></main>;
let content:React.ReactNode;
if(screen==='home')content=<section className="home-content"><p className="eyebrow">Tu ciudad, a tu manera</p><h1>Hola 👋<br/>¿A dónde querés ir hoy?</h1><div className="feature-grid"><Feature icon="⌁" title="Recorridos accesibles" sub="Encontrá el mejor camino" onClick={()=>go('routes')}/><Feature icon="!" title="Reportar una barrera" sub="Ayudá a mejorar la ciudad" onClick={()=>go('report')}/><Feature icon="▶" title="Tutoriales" sub="Consejos para tu autonomía" onClick={()=>go('tutorials')}/></div><button className="how-card" onClick={()=>go('routes')}><span>i</span><span><strong>¿Cómo funciona Rodando X MZA?</strong><small>Elegí un destino y encontrá un recorrido accesible.</small></span><b>›</b></button></section>;
else if(screen==='routes')content=<Page title="Buscá tu recorrido" intro="Elegí un origen y un destino. Priorizaremos veredas y cruces accesibles."><label>Origen<select value={origin} onChange={e=>setOrigin(e.target.value)}>{destinations.map(x=><option key={x}>{x}</option>)}</select></label><button className="swap" onClick={()=>{setOrigin(destination);setDestination(origin)}} aria-label="Intercambiar origen y destino">⇅</button><label>Destino<select value={destination} onChange={e=>setDestination(e.target.value)}>{destinations.map(x=><option key={x}>{x}</option>)}</select></label><Button onClick={()=>go('map')}>Buscar recorrido accesible</Button></Page>;
else if(screen==='map')content=<section className="map-page"><MapVisual/><div className="map-legend"><Badge tone="ok" label="Accesible"/><Badge tone="warn" label="Sin verificar"/><Badge tone="bad" label="No accesible"/></div><article className="route-card"><div className="success-row"><span>✓</span><div><small>RECORRIDO LISTO</small><h2>Ruta accesible encontrada</h2></div></div><div className="stats"><strong>1,2 km</strong><span>•</span><strong>18 min aprox.</strong></div><p>Este recorrido prioriza veredas y cruces registrados como accesibles.</p><div className="notice"><b>!</b> Hay 1 tramo cuya accesibilidad todavía no fue verificada.</div><Button onClick={()=>go('detail')}>Ver detalle</Button><Button secondary onClick={()=>go('routes')}>Cambiar recorrido</Button></article></section>;
else if(screen==='detail')content=<Page title="Detalle del recorrido" intro={`${origin} → ${destination}`}><div className="steps">{routeSteps.map((x,i)=><article className="step" key={x.text}><span className="step-number">{i+1}</span><div><h3>{x.text}</h3><p>{x.detail}</p><Badge tone={x.tone} label={x.state}/></div></article>)}</div><Button onClick={()=>go('map')}>Volver al mapa</Button></Page>;
else if(screen==='report')content=<Page title="Reportar una barrera" intro="Tu aporte puede ayudar a otras personas."><label>Ubicación<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Ej. Av. España y Espejo"/></label><button className="location-button" onClick={()=>setLocation('Ubicación actual · Ciudad de Mendoza')}>⌖ Usar ubicación actual</button><fieldset><legend>Tipo de barrera</legend><div className="chips">{barrierTypes.map(x=><button className={type===x?'selected':''} onClick={()=>setType(x)} key={x}>{x}</button>)}</div></fieldset><label className="photo-box"><span>{photo?'✓ Foto simulada agregada':'▣ Agregar foto'}</span><input type="file" accept="image/*" onChange={()=>setPhoto(true)}/><small>No se abrirá la cámara en este prototipo.</small></label><label>Descripción <em>(opcional)</em><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Contanos brevemente qué encontraste..."/></label><Button disabled={!location||!type} onClick={()=>go('confirm')}>Continuar</Button></Page>;
else if(screen==='confirm')content=<Page title="Confirmar reporte" intro="Revisá la información antes de enviarla."><div className="summary"><Summary label="Ubicación" value={location}/><Summary label="Tipo de barrera" value={type}/><Summary label="Foto" value={photo?'Foto simulada agregada':'Sin foto'}/><Summary label="Descripción" value={description||'Sin descripción'}/></div><Button onClick={async()=>{await api.createReport({location,type,photo,description});go('thanks')}}>Enviar reporte</Button><Button secondary onClick={()=>go('report')}>Editar información</Button></Page>;
else if(screen==='thanks')content=<section className="confirmation"><div className="thanks-icon">✓</div><p className="eyebrow">Reporte enviado</p><h1>¡Gracias por colaborar!</h1><p>Tu reporte fue registrado. En este prototipo, la información no se guarda permanentemente.</p><Button onClick={()=>go('home')}>Volver al inicio</Button></section>;
else if(screen==='tutorials')content=<Page title="Tutoriales" intro="Consejos y técnicas para moverte con mayor autonomía."><div className="tutorial-grid">{tutorials.map(t=><button className="tutorial-card" key={t.id} onClick={()=>{setSelectedTutorial(t);go('tutorial')}}><span>{t.icon}</span><div><h3>{t.title}</h3><small>{t.duration}</small></div><b>›</b></button>)}</div></Page>;
else content=<Page title={selectedTutorial.title} intro="Contenido educativo desarrollado junto a especialistas."><div className="video"><span>▶</span><small>VIDEO · {selectedTutorial.duration}</small></div><h2>{selectedTutorial.title}</h2><p className="body-copy">{selectedTutorial.desc}</p><Button onClick={()=>alert('Reproducción simulada para este prototipo.')}>Reproducir</Button></Page>;
const back=screen==='home'?undefined:()=>go(screen==='detail'?'map':screen==='confirm'?'report':screen==='tutorial'?'tutorials':'home');return <main className="app-shell"><Header title={screen==='home'?undefined:screen==='map'?'Tu recorrido':undefined} onBack={back}/>{content}{!['confirm','thanks','tutorial','routes','detail'].includes(screen)&&<BottomNav screen={screen} go={go}/>}</main>}
function Feature({icon,title,sub,onClick}:{icon:string,title:string,sub:string,onClick:()=>void}){return <button className="feature-card" onClick={onClick}><span className="feature-icon">{icon}</span><span><strong>{title}</strong><small>{sub}</small></span><b>›</b></button>}
function Page({title,intro,children}:{title:string,intro:string,children:React.ReactNode}){return <section className="page-content"><p className="eyebrow">Rodando por Mendoza</p><h1>{title}</h1><p className="page-intro">{intro}</p>{children}</section>}
function Summary({label,value}:{label:string,value:string}){return <div><small>{label}</small><strong>{value}</strong></div>}
